import LegalDocument, { LegalSection } from '@/components/LegalDocument';

const sections: LegalSection[] = [
    { id: 'about', title: '1. About Parentfully', paragraphs: ['Parentfully is a family organization and parenting support app designed to help parents bring more structure, clarity, and alignment into everyday family life.', 'Parentfully may help users manage routines, schedules, skill-based goals for each child, behaviour notes, discipline plans, family communication, family responsibilities, family or child-related financial records, feedback, suggestions, and feature requests.', 'Parentfully is a support and organization tool. It does not replace legal, medical, mental health, educational, financial, or professional advice.'] },
    { id: 'who-can-use', title: '2. Who Can Use Parentfully', paragraphs: ['You must be at least 18 years old to create a Parentfully account.', 'Parentfully is designed for parents, guardians, caregivers, and adults responsible for supporting a child.', 'Children may only use Parentfully with the permission and supervision of a parent or legal guardian, where child-facing features are available.'] },
    { id: 'account', title: '3. Your Account', paragraphs: ['You agree to provide accurate information when creating your account.', 'You are responsible for keeping your login details safe.', 'You are responsible for all activity that happens under your account.', 'You must not share your account with anyone who is not allowed to access your family or child-related information.', 'If you believe someone has accessed your account without permission, contact us immediately at admin@parentfullyapp.com.'] },
    { id: 'family', title: '4. Family Members, Co-Parents, and Caregivers', paragraphs: ['Parentfully may allow you to invite another parent, co-parent, guardian, caregiver, or family member to your family space.', 'You are responsible for making sure you have the right to invite that person and share child-related information with them.', 'You should not add anyone who is not legally or practically allowed to access the child’s information.', 'Parentfully is not responsible for disagreements between parents, co-parents, guardians, or caregivers about access to information.'] },
    { id: 'content', title: '5. Your Content', paragraphs: ['You may add information to Parentfully, including routines, schedules, skill-based goals for each child, behaviour notes, parenting notes, communication, expenses, photos, feedback, feature requests, suggestions, or other family-related content.', 'You are responsible for the content you add.', 'You agree not to upload content that is false, harmful, threatening, abusive, illegal, harassing, or that violates another person’s rights.', 'You also agree not to upload private information that you do not have permission to share.', 'By using Parentfully, you give us permission to store, process, and display your content only as needed to provide the service.', 'We do not own your family content.'] },
    { id: 'feedback', title: '6. Feedback, Suggestions, and Feature Requests', paragraphs: ['Parentfully may allow users to leave feedback, request features, or make suggestions inside the app.', 'By submitting feedback, ideas, or suggestions, you give Parentfully permission to review, use, improve, develop, or include those ideas in the app or business without payment or obligation to you.', 'You should not submit confidential information through the feedback feature unless you are comfortable sharing it with us.'] },
    { id: 'safety', title: '7. Child Safety', paragraphs: ['Parentfully is designed to support families and child wellbeing.', 'You agree not to use Parentfully in any way that harms, exploits, threatens, abuses, or endangers a child.', 'If we believe Parentfully is being used in a way that may seriously harm a child or another person, we may suspend or terminate access and take any action required or allowed by law.'] },
    { id: 'guidance', title: '8. Parenting, Discipline, and Family Guidance', paragraphs: ['Parentfully may provide tools, prompts, templates, reminders, or educational content related to parenting, routines, discipline, child development, communication, or family life.', 'This content is for general support and organization only.', 'Parentfully does not guarantee a specific parenting outcome.', 'You are responsible for deciding what is appropriate for your child and family.', 'For serious concerns about your child’s health, safety, behaviour, education, or mental wellbeing, please speak with a qualified professional.'] },
    { id: 'legal', title: '9. Co-Parenting and Legal Matters', paragraphs: ['Parentfully may help parents organize communication, schedules, expenses, responsibilities, and records.', 'Parentfully does not provide legal advice.', 'Parentfully does not decide custody, parenting time, child support, access rights, or legal responsibilities.', 'You are responsible for following any court order, parenting agreement, custody arrangement, or legal obligation that applies to your family.'] },
    { id: 'expenses', title: '10. Expenses and Financial Records', paragraphs: ['Parentfully may allow users to record child-related expenses, contributions, payments, reimbursements, or financial responsibilities.', 'Parentfully is not a bank, payment provider, accountant, or financial advisor.', 'Any financial information entered into Parentfully is for organization and tracking only.', 'You are responsible for checking that all amounts, payments, and records are correct.'] },
    { id: 'permissions', title: '11. Permissions', paragraphs: ['Parentfully may ask for certain device permissions to make the app work properly. These may include contact access, camera access, alarm access, and notification access.', 'You can manage some permissions through your device settings.', 'Some features may not work properly if you turn off required permissions.'] },
    { id: 'acceptable-use', title: '12. Acceptable Use', paragraphs: ['You agree not to:'], bullets: ['use Parentfully for illegal purposes;', 'access another user’s account without permission;', 'misuse communication tools to harass, threaten, control, or intimidate another person;', 'upload harmful code, spam, or viruses;', 'copy, damage, reverse engineer, or interfere with the app;', 'collect information from other users without permission;', 'use Parentfully in a way that may harm a child, parent, caregiver, or family member.'] },
    { id: 'payments', title: '13. Subscriptions, Payments, and Free Trials', paragraphs: ['Some Parentfully features may be free. Other features may require payment.', 'If Parentfully offers a free trial, the terms of the trial will be shown at sign-up.', 'Paid plans, renewal dates, cancellation rules, and refund policies may depend on where you purchased your subscription, including Google Play Store, Apple App Store, or the Parentfully website.', 'You are responsible for cancelling before renewal if you do not want to continue a paid plan.', 'Fees may change in the future. We will give notice where required.'] },
    { id: 'app-store', title: '14. App Store Terms', paragraphs: ['If you download Parentfully from Google Play Store, Apple App Store, or another app marketplace, you may also be subject to that store’s terms and policies.', 'If there is a conflict between these Terms and the app store’s rules, the app store’s rules may apply to app store payments, downloads, refunds, and account management.'] },
    { id: 'ip', title: '15. Intellectual Property', paragraphs: ['Parentfully, including its name, logo, designs, content, systems, templates, features, and materials, belongs to Parentfully or its owners.', 'You may not copy, sell, reproduce, modify, or distribute Parentfully materials without written permission.', 'You may use Parentfully only for your personal family use unless we give written permission for another use.'] },
    { id: 'availability', title: '16. Service Availability', paragraphs: ['We work to keep Parentfully available and useful, but we do not guarantee that the app will always be available, error-free, secure, or uninterrupted.', 'We may update, change, suspend, or remove parts of Parentfully at any time.'] },
    { id: 'deletion', title: '17. Account Deletion', paragraphs: ['You may delete your account inside the Parentfully app.', 'When you delete your account, your account information and related data may be deleted or deactivated, subject to legal, security, backup, dispute resolution, or recordkeeping requirements.', 'Some deleted information may remain in backups for a limited time before being fully removed.'] },
    { id: 'termination', title: '18. Account Suspension or Termination', paragraphs: ['We may suspend or terminate your account if you break these Terms, misuse the app, create safety risks, harm another person, or use Parentfully in a way that may harm a child.', 'You may stop using Parentfully at any time.'] },
    { id: 'liability', title: '19. Limitation of Liability', paragraphs: ['To the fullest extent allowed by law, Parentfully is not responsible for indirect, accidental, special, or consequential losses.', 'Parentfully is not responsible for parenting decisions, co-parenting conflicts, family disputes, missed schedules, incorrect records, or outcomes based on your use of the app.', 'You use Parentfully at your own discretion.'] },
    { id: 'changes', title: '20. Changes to These Terms', paragraphs: ['We may update these Terms from time to time.', 'If we make important changes, we may notify you through the app, email, or website.', 'Your continued use of Parentfully after changes means you accept the updated Terms.'] },
    { id: 'contact', title: '21. Contact Us', paragraphs: ['For questions about these Terms, contact us at:', 'Parentfully / Pilandres Solutions Inc.\n350 Boulevard de Maisonneuve Ouest\nH3A 0B4\nMontreal, Quebec, Canada\nEmail: admin@parentfullyapp.com\nWebsite: parentfullyapp.com'] },
];

export default function TermsOfUsePage() {
    return <LegalDocument eyebrow="Legal agreement" title="Terms of Use" summary="These Terms of Use explain the rules for using Parentfully, including the Parentfully mobile app, website, and related services." lastUpdated="6 June 2026" sections={sections} />;
}
